In [35]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

| 컬럼명                     | 설명                            |
|---------------------------|---------------------------------|
| ID                        | 샘플별 고유 ID                   |
| gender                    | 성별                             |
| age                       | 연령                             |
| height                    | 키 (cm)                          |
| weight                    | 몸무게 (kg)                      |
| cholesterol               | 콜레스테롤 수치                  |
| systolic_blood_pressure   | 수축기 혈압                      |
| diastolic_blood_pressure  | 이완기 혈압                      |
| glucose                   | 혈당 수치 (mg/dL)               |
| bone_density              | 골밀도 (g/cm²)                   |
| activity                  | 생활 시 운동 강도                |
| smoke_status              | 흡연 상태                        |
| medical_history           | 만성질환                         |
| family_medical_history    | 가족력                           |
| sleep_pattern             | 수면 패턴                        |
| edu_level                 | 학력                             |
| mean_working              | 1주일당 평균 근로 시간           |
| stress_score              | **(TARGET)** 스트레스 점수       |

In [36]:
train = pd.read_csv("./data1/train.csv")
X_test = pd.read_csv("./data1/test.csv")

train

,ID,gender,age,height,weight,cholesterol,systolic_blood_pressure,diastolic_blood_pressure,glucose,bone_density,activity,smoke_status,medical_history,family_medical_history,sleep_pattern,edu_level,mean_working,stress_score
0,TRAIN_0000,F,72,161.49,58.47,279.84,165,100,143.35,0.87,moderate,ex-smoker,high blood pressure,diabetes,sleep difficulty,bachelors degree,NaN,0.63
1,TRAIN_0001,M,88,179.87,77.60,257.37,178,111,146.94,0.07,moderate,ex-smoker,NaN,diabetes,normal,graduate degree,NaN,0.83
2,TRAIN_0002,M,47,182.47,89.93,226.66,134,95,142.61,1.18,light,ex-smoker,NaN,NaN,normal,high school diploma,9.0,0.70
3,TRAIN_0003,M,69,185.78,68.63,206.74,158,92,137.26,0.48,intense,ex-smoker,high blood pressure,NaN,oversleeping,graduate degree,NaN,0.17
4,TRAIN_0004,F,81,164.63,71.53,255.92,171,116,129.37,0.34,moderate,ex-smoker,diabetes,diabetes,sleep difficulty,bachelors degree,NaN,0.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,TRAIN_2995,F,87,174.43,77.14,233.31,176,111,134.71,0.20,light,non-smoker,NaN,NaN,oversleeping,NaN,NaN,0.02
2996,TRAIN_2996,M,25,171.44,51.67,196.89,143,86,111.91,1.75,moderate,current-smoker,NaN,NaN,normal,high school diploma,9.0,0.16
2997,TRAIN_2997,F,54,162.13,55.54,210.52,164,91,136.47,0.80,light,current-smoker,NaN,NaN,normal,NaN,9.0,0.16
2998,TRAIN_2998,M,70,181.32,82.20,234.10,182,91,144.89,0.58,moderate,non-smoker,NaN,NaN,oversleeping,high school diploma,NaN,0.18
2999,TRAIN_2999,M,86,179.46,69.31,254.63,149,94,154.92,0.45,moderate,ex-smoker,high blood pressure,heart disease,normal,NaN,NaN,0.04

In [37]:
print(train.shape, X_test.shape)

(3000, 18) (3000, 17)

In [38]:
X = train.drop(['stress_score'], axis=1)
y = train['stress_score']

print(X.shape, y.shape)

X

(3000, 17) (3000,)

,ID,gender,age,height,weight,cholesterol,systolic_blood_pressure,diastolic_blood_pressure,glucose,bone_density,activity,smoke_status,medical_history,family_medical_history,sleep_pattern,edu_level,mean_working
0,TRAIN_0000,F,72,161.49,58.47,279.84,165,100,143.35,0.87,moderate,ex-smoker,high blood pressure,diabetes,sleep difficulty,bachelors degree,NaN
1,TRAIN_0001,M,88,179.87,77.60,257.37,178,111,146.94,0.07,moderate,ex-smoker,NaN,diabetes,normal,graduate degree,NaN
2,TRAIN_0002,M,47,182.47,89.93,226.66,134,95,142.61,1.18,light,ex-smoker,NaN,NaN,normal,high school diploma,9.0
3,TRAIN_0003,M,69,185.78,68.63,206.74,158,92,137.26,0.48,intense,ex-smoker,high blood pressure,NaN,oversleeping,graduate degree,NaN
4,TRAIN_0004,F,81,164.63,71.53,255.92,171,116,129.37,0.34,moderate,ex-smoker,diabetes,diabetes,sleep difficulty,bachelors degree,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,TRAIN_2995,F,87,174.43,77.14,233.31,176,111,134.71,0.20,light,non-smoker,NaN,NaN,oversleeping,NaN,NaN
2996,TRAIN_2996,M,25,171.44,51.67,196.89,143,86,111.91,1.75,moderate,current-smoker,NaN,NaN,normal,high school diploma,9.0
2997,TRAIN_2997,F,54,162.13,55.54,210.52,164,91,136.47,0.80,light,current-smoker,NaN,NaN,normal,NaN,9.0
2998,TRAIN_2998,M,70,181.32,82.20,234.10,182,91,144.89,0.58,moderate,non-smoker,NaN,NaN,oversleeping,high school diploma,NaN
2999,TRAIN_2999,M,86,179.46,69.31,254.63,149,94,154.92,0.45,moderate,ex-smoker,high blood pressure,heart disease,normal,NaN,NaN

In [39]:
X.isnull().sum() # 결측치 확인 ['medical_history', 'family_medical_history', 'edu_level', 'mean_working' ]

ID                             0
gender                         0
age                            0
height                         0
weight                         0
cholesterol                    0
systolic_blood_pressure        0
diastolic_blood_pressure       0
glucose                        0
bone_density                   0
activity                       0
smoke_status                   0
medical_history             1289
family_medical_history      1486
sleep_pattern                  0
edu_level                    607
mean_working                1032
dtype: int64

In [40]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        3000 non-null   object
 1   gender                    3000 non-null   object
 2   age                       3000 non-null   int64
 3   height                    3000 non-null   float64
 4   weight                    3000 non-null   float64
 5   cholesterol               3000 non-null   float64
 6   systolic_blood_pressure   3000 non-null   int64
 7   diastolic_blood_pressure  3000 non-null   int64
 8   glucose                   3000 non-null   float64
 9   bone_density              3000 non-null   float64
 10  activity                  3000 non-null   object
 11  smoke_status              3000 non-null   object
 12  medical_history           1711 non-null   object
 13  family_medical_history    1514 non-null   object
 14  sleep_pattern             3000 non-null   object
 15  edu_level                 2393 non-null   object
 16  mean_working              1968 non-null   float64
dtypes: float64(6), int64(3), object(8)
memory usage: 398.6+ KB

In [41]:
print(type(X), type(y))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>

In [42]:
X.corrwith(y, numeric_only=True) # y에 대한 상관계수 확인 mean_working 외에는 약한 상관계수를 보이고 있음

age                         0.018656
height                     -0.005664
weight                      0.011328
cholesterol                 0.021288
systolic_blood_pressure     0.015635
diastolic_blood_pressure    0.025351
glucose                    -0.006083
bone_density               -0.022556
mean_working                0.183433
dtype: float64

In [43]:
X.corrwith(y, numeric_only=True).index[:-1]

Index(['age', 'height', 'weight', 'cholesterol', 'systolic_blood_pressure',
       'diastolic_blood_pressure', 'glucose', 'bone_density'],
      dtype='object')

In [44]:
X['activity'].value_counts()

activity
moderate    1431
light        894
intense      675
Name: count, dtype: int64

In [ ]:
activity_map = {
    'light' : 0,
    'moderate' : 1,
    'intense' : 2,
}
X['activity'] = X['activity'].map(activity_map)
X['activity']

0       1
1       1
2       0
3       2
4       1
       ..
2995    0
2996    1
2997    0
2998    1
2999    1
Name: activity, Length: 3000, dtype: int64

In [47]:
X['smoke_status'].value_counts()

smoke_status
ex-smoker         1177
non-smoker        1039
current-smoker     784
Name: count, dtype: int64